"use client"

import { useEffect } from "react"
import { Button } from "@/components/ui/button"
import { ChevronLeft } from 'lucide-react'
import { motion } from "framer-motion"
import { fadeIn, staggerContainer } from "@/lib/framer-animations"
import { ImageCarousel } from "@/components/image-carousel"
import { useRouter } from 'next/navigation'

const projects = {
  "mekari-sign": {
    title: "Mekari Sign",
    role: "Product Manager",
    period: "2023",
    description: "Led the development and growth of Mekari's e-signature solution, achieving 134% revenue target and expanding market presence.",
    impact: [
      "134.04% revenue target achievement",
      "4.5/5.0 client satisfaction score",
      "30% reduction in onboarding time",
      "20% market share growth"
    ],
    details: "As Product Manager for Mekari Sign, I worked with cross-functional teams to streamline user and team management processes, optimize API integration for enterprise clients, and drive significant revenue growth through strategic product development and market expansion initiatives. Key features implemented include secure document signing with passcode protection, foreigner eKYC verification, multiple certificate management, and comprehensive signing analytics.",
    images: [
      {
        src: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-OPGGmbr7Fc0eZx2YyacbMMjd7pkl4s.png",
        alt: "Passcode protection feature for secure document signing"
      },
      {
        src: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-rC3uJsaznVwn54VrB1Wy4aD8D2kYT4.png",
        alt: "Foreigner eKYC verification system"
      },
      {
        src: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-1NAPaCendBhR1tOYmcd1xXzMXprZZF.png",
        alt: "Multiple certificate management interface"
      },
      {
        src: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-lsa9Wh3kwrJtPw7mkhncvn3boHmO5k.png",
        alt: "Signing insights and analytics dashboard"
      },
      {
        src: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-m8Gu6ZihYae2AMf6I7r8SGOi0l10r5.png",
        alt: "Main dashboard interface of Mekari Sign"
      }
    ]
  },
  "shopee-seller": {
    title: "Shopee Seller Growth",
    role: "Associate Product Manager",
    period: "2022",
    description: "Specialized in Seller Growth and Marketing Tools, driving significant improvements in seller acquisition and retention.",
    impact: [
      "20% increase in seller acquisition",
      "15% increase in retention rate",
      "25% increase in product satisfaction",
      "50+ successful user interviews"
    ],
    details: "Led product initiatives for seller growth and marketing tools, conducting extensive user research and implementing features that significantly improved seller satisfaction and platform adoption.",
    images: [
      {
        src: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-v1WfB1wnc3y8PBdVhbL9EdpjRDJChO.png",
        alt: "Shopee Seller Center Dashboard showing business insights and metrics"
      },
      {
        src: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-vFCAZvwAATlPfFFgAMHg9vnPOcjR5l.png",
        alt: "Shopee Seller Benefits Management Interface"
      }
    ]
  },
  "ibm-rpa": {
    title: "IBM Process Automation",
    role: "Software Specialist",
    period: "2020-2022",
    description: "Led digital transformation through RPA implementation, achieving remarkable efficiency improvements.",
    impact: [
      "144x task efficiency improvement",
      "60% team efficiency increase",
      "8 automated workflows",
      "25% customer acquisition increase"
    ],
    details: "Spearheaded the automation of high-volume tasks using IBM RPA and Python, leading a team of 4 to implement solutions that dramatically improved operational efficiency.",
    images: [
      {
        src: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-wAV2XYGJoK4SKeurle3KibmDb9uO6e.png",
        alt: "IBM RPA Studio Interface showing automation script"
      },
      {
        src: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-a3SscM2WDSfMdBmYaJAo7nDdAjU5xF.png",
        alt: "IBM Cloud Pak for Business Automation architecture"
      },
      {
        src: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-oByGXmSnP4wvzQAyiOTueiy0lUzPtR.png",
        alt: "Automated email report generated by IBM RPA"
      },
      {
        src: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-yxLsktDsBcjKEds0txuondOTXSWMtL.png",
        alt: "IBM Certified Developer - Robotic Process Automation certification"
      }
    ],
  },
  "jlr-connected": {
    title: "JLR Connected Platform",
    role: "Product Manager",
    period: "2023",
    description: "Developed connected car platform features enhancing vehicle connectivity and user experience.",
    impact: [
      "Platform feature development",
      "Cross-team collaboration",
      "Technical implementation",
      "User experience enhancement"
    ],
    details: "Collaborated on connected car platform development, focusing on feature implementation and user experience optimization."
  }
}

export default function WorkDetail({ params }: { params: { slug: string } }) {
  const router = useRouter()
  const project = projects[params.slug as keyof typeof projects]
  
  useEffect(() => {
    window.scrollTo(0, 0)
  }, [])

  const handleBack = () => {
    router.back()
  }

  if (!project) return null

  return (
    <motion.article 
      initial="initial"
      animate="animate"
      variants={staggerContainer}
      className="py-20"
    >
      <div className="container mx-auto px-4">
        <div className="max-w-3xl mx-auto">
          <motion.div variants={fadeIn}>
            <Button 
              onClick={handleBack} 
              variant="ghost" 
              className="mb-8"
            >
              <ChevronLeft className="mr-2 h-4 w-4" />
              Back
            </Button>
          </motion.div>

          <motion.div variants={fadeIn} className="space-y-8">
            <div>
              <h1 className="font-heading text-4xl font-bold mb-4">{project.title}</h1>
              <div className="flex gap-4 text-muted-foreground">
                <span>{project.role}</span>
                <span>•</span>
                <span>{project.period}</span>
              </div>
            </div>

            <p className="text-xl leading-relaxed">{project.description}</p>

            <div>
              <h2 className="font-heading text-2xl font-semibold mb-4">Impact & Results</h2>
              <ul className="grid sm:grid-cols-2 gap-4">
                {project.impact.map((item, index) => (
                  <li key={index} className="bg-muted p-4 rounded-lg">
                    {item}
                  </li>
                ))}
              </ul>
            </div>

            <div>
              <h2 className="font-heading text-2xl font-semibold mb-4">Project Details</h2>
              <p className="text-muted-foreground">{project.details}</p>
            </div>
            {project.images && (
              <motion.div variants={fadeIn} className="mt-12">
                <h2 className="font-heading text-2xl font-semibold mb-8">Project Gallery</h2>
                <ImageCarousel images={project.images} />
              </motion.div>
            )}
          </motion.div>
        </div>
      </div>
    </motion.article>
  )
}

